name: php-cs-fixer

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest


    outputs:
      backgound-output: ${{ steps.background-step.output}}

        
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Create file
      run: |
        touch abc.txt
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply php-cs-fixer changes
    - name: Run backgroudn step
      id: background-step
      run: echo "im running in background" &
    
    - name: Get backgroudn step output
      run: echo "${{ steps.background-step.outputs.backgound-output}}"


    - name: Get today's date
      uses: mathiasvr/command-output@v1
      id: today
      with:
        run: echo "im running in background" &

    - run: echo Today is ${{ steps.background-step.outputs.stdout }}



