name: php-cs-fixer

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Create file
      run: |
        printf "Hello\nWorld\n" > hw.txt
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        tagging_message: 'v1.0.0'
        commit_message: Apply php-cs-fixer changes