name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-job-1:
    runs-on: ubuntu-latest

    steps:




    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

  

    - uses: actions/setup-node@v3
      with:
        node-version: 16



    - run: npm install


  
    - run: npm run start0 >> logs/$(date +%y-%m-%d-%T)_server0.aaa &
    - run: npm run start1 >> logs/$(date +%y-%m-%d-%T)_server1.bbb &
    - run: npm run start2 >> logs/$(date +%y-%m-%d-%T)_server2.ccc &




    - run: npm test





    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: logs for 3 servers

