name: php-cs-fixer

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest


    outputs:
      backgound-output: ${{ steps.background-step.output}}

        
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Create file
      run: |
        touch abc.txt
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply php-cs-fixer changes
    - name: Run backgroudn step
      id: background-step
      run: echo "im running in background" &
    - name: Get backgroudn step output
      run: echo "${{ steps.background-step.outputs.backgound-output}}"




    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm start &


  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - id: step1
        run: |
            echo "::group::My title" >> $GITHUB_OUTPUT
            echo $(npm test) >> $GITHUB_OUTPUT
            echo "::endgroup::" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}