name: php-cs-fixer

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest


    outputs:
      backgound-output: ${{ steps.background-step.output}}

        
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Create file
      run: |
        touch abc.txt
   
    - name: Run backgroudn step
      id: background-step
      run: echo "im running in background" &
    - name: Get backgroudn step output
      run: echo "${{ steps.background-step.outputs.backgound-output}}"




    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
  
    - run:  npm start >> abc.txt &
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply php-cs-fixer changes

