
name: toolkit-sample

on:
  pull_request:
  push:
    branches:
      - main

env:
  context: Monday

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.set-output.outputs.output1 }}
    steps:
      - uses: actions/github-script@v5
        id: set-output
        with:
          script: |
            # Assuming we have a `content` environment variable or output of previous step
            core.setOutput("output1", `${{ env.context }}`);            
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: |
        echo "Output1: ${{ needs.job1.outputs.output1 }}"